---
- name: Install nginx
  apt:
    name: nginx-light
    state: latest

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - Reload nginx

- name: Set up tmpfs for Nginx caching of responses to prevent thrashing SD card
  mount:
    path: /var/nginx/cache
    fstype: tmpfs
    src: tmpfs
    state: mounted
    # UID/GID 33 are for `www-data`, the Nginx default on Debian
    # We also enforce a max size here, because apparently Nginx's max size
    # param for cache sizing is not 100% honored.
    opts: rw,size=64M,nr_inodes=50k,noexec,nodev,nosuid,uid=33,gid=33,mode=1700
  notify:
    - Restart nginx

- name: Manage nginx configuration for kiwix
  copy:
    src: kiwix.conf
    dest: /etc/nginx/conf.d/kiwix.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload nginx
