---
- name: Checkout latest kiwix-tools
  git:
    repo: https://github.com/kiwix/kiwix-tools.git
    dest: "{{ data_volume }}/kiwix-tools"
    version: 3.0.3

# We only build with 1 thread to prevent thrashing IO on small
# devices like Raspberry Pis
- name: Build & install kiwix-tools
  shell: |
    meson . build
    ninja -j 1 -C build install
  args:
    chdir: "{{ data_volume }}/kiwix-tools"
