---
# Install binary dependencies from upstream
- include_tasks: deps.yml

# Install libzim from source
- include_tasks: libzim.yml

# Install kiwix-lib from source
- include_tasks: kiwix-lib.yml

# Install kiwix-tools from source
- include_tasks: kiwix-tools.yml

- name: Make kiwix user
  user:
    name: kiwix

- name: Create kiwix library
  shell: |
    for i in $(ls {{ data_volume }}/*.zim); do
      kiwix-manage {{ data_volume }}/library.xml add ${i}
    done

- name: Configure kiwix logging to prevent thrashing an SD card
  copy:
    src: journald@kiwix.conf
    dest: /etc/systemd/journald@kiwix.conf
    owner: root
    group: root
    mode: '0644'

- name: Activate kiwix logging
  systemd:
    name: systemd-journald
    state: restarted

- name: Create kiwix service
  template:
    src: kiwix-serve.service
    dest: /etc/systemd/system/kiwix-serve.service
    owner: root
    group: root
    mode: '0644'

- name: Enable and start kiwix-serve service
  systemd:
    name: kiwix-serve
    state: started
    enabled: yes
    daemon_reload: yes
